# Generated by Django 5.2.9 on 2026-05-22 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('titulo_gl', models.CharField(blank=True, max_length=200, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('descripcion_gl', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('ofertas', 'Ofertas'), ('vendido', 'Lo más vendido'), ('limitado', 'Por tiempo limitado'), ('ninguna', 'Ninguna')], default='ninguna', max_length=20)),
                ('in_trash', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(default='usuario_generico', max_length=150, unique=True)),
                ('password', models.CharField(default='', max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
