# Generated by Django 5.2.13 on 2026-05-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('ofertas', 'Ofertas'), ('limitado', 'Por tiempo limitado'), ('vendido', 'Lo mas vendido'), ('ninguna', 'Ninguna')], default='ninguna', max_length=20)),
            ],
        ),
    ]
