# Generated by Django 5.2.9 on 2026-05-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='in_trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('ofertas', 'Ofertas'), ('vendido', 'Lo más vendido'), ('limitado', 'Por tiempo limitado'), ('ninguna', 'Ninguna')], default='ninguna', max_length=20),
        ),
    ]
