# Generated by Django 5.2.9 on 2026-05-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_in_trash_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion_gl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='titulo_gl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
